### ISSUE TITLE
Radiometer not measuring with error: OSError: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/libstdc++.so.6)

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#27]
When trying to measure using the gui, I am getting:

```
[hypernets@hypernets-cnr1 hypernets_tools]$ python -m hypernets.gui
29.18'C   23.6% RH   1011.66mbar   90.5lx
Position : 0°0'0"N 0°0'0"E
Datetime : N/A
offset_tilt : 60
offset_pan: 0
offset_tilt : 60
offset_pan: 0
VNIR Irradiance 8 0 1 0 2592 x 1944, 5MP
--> [1 2 8 0] x 1
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/hypernets/hypernets_tools/hypernets/gui/frame_radiometer.py", line 155, in general_callback
    output = take_spectra(None, path.join(output_dir, output_name),
  File "/home/hypernets/hypernets_tools/hypernets/scripts/call_radiometer.py", line 123, in take_spectra
    instrument_instance = instanciation()
  File "/home/hypernets/hypernets_tools/hypernets/scripts/call_radiometer.py", line 37, in instanciation
    instrument_instance = Hypstar(instrument_port)
  File "/home/hypernets/hypernets_tools/hypernets/scripts/libhypstar/python/hypstar_wrapper.py", line 35, in __init__
    self.lib = CDLL('libhypstar.so')
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/libstdc++.so.6)
```

I am not sure if it related to this, but when I am trying to reinstall 01_dependencies.sh:

```
[hypernets@hypernets-cnr1 install]$ ./01_dependencies.sh 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
warning: python-pip-20.3.1-1 is up to date -- reinstalling
warning: tk-8.6.11.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
 
Packages (2) python-pip-20.3.1-1  tk-8.6.11.1-1
 
Total Installed Size:  6,37 MiB
Net Upgrade Size:      0,00 MiB
 
:: Proceed with installation? [Y/n] Y
(2/2) checking keys in keyring                                       [######################################] 100%
(2/2) checking package integrity                                     [######################################] 100%
(2/2) loading package files                                          [######################################] 100%
(2/2) checking for file conflicts                                    [######################################] 100%
(2/2) checking available disk space                                  [######################################] 100%
:: Processing package changes...
(1/2) reinstalling python-pip                                        [######################################] 100%
(2/2) reinstalling tk                                                [######################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3.1', 'console_scripts', 'pip')())
  File "/usr/bin/pip", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pip
```

**Comment by corizzi** [comment]
Hi @javierconcha , 

Can you give the outputs of the following commands please : 
`python -m pip -V`

**Comment by jkuusk** [comment]
Most likely you have broken dependencies between the system packages after installing make and its dependencies, but not doing full system update. That should be fixed after running pacman -Syu, but prepare for broken python after that because python will be updated from 3.8 to 3.9. Although the latest libhypstar doesn't use libboost any more, I believe there are still going to be some issues with the pyhon's ftdi serial driver package. See also #7

**Comment by javierconcha** [comment]
> python -m pip -V

[hypernets@hypernets-cnr1 hypernets_tools]$ python -m pip -V
/usr/bin/python: No module named pip

**Comment by javierconcha** [comment]
> Most likely you have broken dependencies between the system packages after installing make and its dependencies, but not doing full system update. That should be fixed after running pacman -Syu, but prepare for broken python after that because python will be updated from 3.8 to 3.9. Although the latest libhypstar doesn't use libboost any more, I believe there are still going to be some issues with the pyhon's ftdi serial driver package. See also #7
Thanks @jkuusk!

@corizzi, do you recommend @jkuusk solution?

**Comment by corizzi** [comment]
Yes, you will probably have to reinstall the dependencies too after update. So you can try this :
`sudo pacman -Syu`
`sudo reboot`
`cd hypernets_tools`
`git pull`
`./install/01_dependencies.sh`

**Comment by javierconcha** [comment]
I followed these instructions and the problem was solved. I have not had any problem after updating to Python 3.9 so far.
